version: "latest"

services:
  web-ddx:
    build:
      context: ./
      dockerfile: ./docker/web/Dockerfile

    ports:
      - "8080:80"

    networks:
      - ddx-net

    volumes:
      - ./docker/web/public_html:/usr/local/apache2/htdocs:r

  flaskapp-ddx:
    build:
      context: ./
      dockerfile: ./docker/api/Dockerfile

    ports:
      - "5050:5050"

    networks:
      - ddx-net

    volumes:
      - ./bots:/bots:r
      - /var/run/docker.sock:/var/run/docker.sock:rw

networks:
  ddx-net:
    name: ddx-net
    driver: bridge
